### ISSUE TITLE
More

### ISSUE THREAD

**Issue by scriptex** [scriptex/scss-goodies#15]
1. z-index management
```scss

// Function
@function z($name, $z-indexes-list: $z-indexes) {
 @if index($z-indexes-list, $name) {
 @return (length($z-indexes-list) - index($z-indexes-list, $name)) + 1;
 } @else {
 @warn 'There is no item "#{$name}" in this list; choose one of: #{$z-indexes-list}';
 
 @return null;
 }
}
 
// List
$z-indexes: (
 'modal',
 'site-nav',
 'site-header',
 'site-content',
 'site-footer'
);
 
// Example
.modal { z-index: z(modal); }
.site-nav { z-index: z(site-nav); }
.site-header { z-index: z(site-header); }
.site-content { z-index: z(site-content); }
.site-footer { z-index: z(site-footer; }
 
// Output
.modal { z-index: 5; }
.site-nav { z-index: 4; }
.site-header { z-index: 3; }
.site-content { z-index: 2; }
.site-footer { z-index: 1; }
```

2. Half numbers
```scss
// Function
@function h($num) {
 @return $num / 2;
}
 
// Example
.example {
 width: $element-width;
 height: h($element-width);
}
 
// Output
.example {
 width: 100px;
 height: 50px;
}
```

3. Negative numbers
```scss
// Function
@function n($num) {
 @return 0 - $num;
}
 
// Example
.example {
 top: n($element-width);
}
 
// Output
.example {
 top: -100px;
}
```

4.Half negative numbers
```scss
// Function
@function hn($num) {
 @return n(h($num));
}
 
// Example
.example {
 position: absolute;
 width: $element-width;
 left: 50%;
 transform: translateX(hn($element-width));
}
 
// Output
.example {
 position: absolute;
 width: 100%;
 left: 50%;
 transform: translateX(-50px);
}
```

5. Margin and padding helper classes
```scss
$spaceamounts: (0, 10, 20, 30, 50);
$sides: (top, bottom, left, right, all);

@each $space in $spaceamounts {
  @each $side in $sides {

    @if $side == 'all' {
      .m#{$space} {
        margin: #{$space}px;
      }

      .p#{$space} {
        padding: #{$space}px;
      }
    } @else {
      .m#{str-slice($side, 0, 1)}#{$space} {
        margin-#{$side}: #{$space}px;
      }

      .p#{str-slice($side, 0, 1)}#{$space} {
        padding-#{$side}: #{$space}px;
      }
    }
  }
}
```

6. Lighten and darken
```scss
// slightly lighten
@function tint($color, $percentage) {
  @return mix(white, $color, $percentage);
}

// slightly darken
@function shade($color, $percentage) {
  @return mix(black, $color, $percentage);
}
```
